# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: yarn install

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: yarn lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: yarn test

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build package
        run: yarn build
